### ISSUE TITLE
BUG: Extra node in the graph that should not be there

### ISSUE THREAD

**Issue by AVanDeBrook** [AVanDeBrook/c-dependency-graph#71]
### Issue
* There is (what I am calling) a rogue node floating around the graph that is not part of a module (specifically the `__attribute__` node)

### Cause
* If what I'm reading is correct, it looks like the node is being created and just ignored (it may be destroyed by the garbage collector, I'm honestly not sure)
* The node is never being added to a module, which is correct behavior
* There seem to be edges which still reference the `__attribute__` node due to the way the edge definitions are parsed and created. According to the Graphviz documentation, if a previously undefined node is referenced in an edge definition, then that node will be created with the `node_id` as its label 

### (Potential) Solution
* Nothing definite, but I have ideas:
  * Changes could be made to either the `Parser` or the `GraphWriter` to work around the problem
  * Since the `__attribute__` node _shouldn't_ have a corresponding object, then a `null` check could be added to the `GraphWriter` when it's creating the `edge_def`s. If either the source or destination node object references are null, then edge will be ignored
  * Some of the "clean up" sections of the `Parser` could be modified or appended to handle the `__attribute__` edge case. I don't have specifics on this yet. I need to read the "clean up" code more thoroughly to figure out the best approach

**Comment by spoofaloof** [comment]
in the clean up nodes function we have to check for this node .. if  it exists, dont add it to the global collection 
in the clean up edges function as a result we will have src/dst nodes which wont have an already existing node in the global context (the nodes check to see if they exist in the global context by name to update their ids -- all nodes should already be in the global context because of ordering), these edges should not be added to their global collection
